package com.app.dto;

import javax.validation.constraints.Email; // Import for email validation
import javax.validation.constraints.NotBlank; // Import for not blank validation
import javax.validation.constraints.NotNull; // Import for not null validation
import lombok.Data;

@Data
public class LoginDTO {
    
    @NotNull(message = "ID cannot be null") // Validate that id cannot be null
    private int id;
    
    @NotBlank(message = "Email cannot be empty") // Validate that email cannot be empty
    @Email(message = "Email should be valid") // Validate that email format is correct
    private String email;
    
    @NotBlank(message = "Name cannot be empty") // Validate that name cannot be empty
    private String name;

    // Constructor for LoginDTO
    public LoginDTO(int id, String email, String name) {
        this.id = id;
        this.email = email;
        this.name = name;
    }

    // Getters and Setters are automatically generated by Lombok's @Data annotation
}
